"""empty message

Revision ID: 688df9ad21de
Revises: 
Create Date: 2024-03-08 09:34:21.365332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688df9ad21de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.Column('carbohydrates', sa.Integer(), nullable=False),
    sa.Column('fat', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_date',
    sa.Column('log_date', sa.Integer(), nullable=True),
    sa.Column('food', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food'], ['food.id'], ),
    sa.ForeignKeyConstraint(['log_date'], ['log_date.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_date')
    op.drop_table('log_date')
    op.drop_table('food')
    # ### end Alembic commands ###
